LOAD DATA
INFILE *
INTO TABLE dept
FIELDS TERMINATED BY ','
(deptno,dname,loc)

BEGINDATA
12,"RESEARCH","SARATOGA"
10,"ACCOUNTING","CLEVELAND"
11,"ART","SALEM"
13,"FINANCE","BOSTON"
21,"SALES","PHILA"
22,"SALES","ROCHESTER"
42,"INTL","SAN FRAN"